# sample docker-compose.yml to create a latex container
version: '3.9'
services:
  latex:
    build:
      context: .
      dockerfile: Dockerfile
    image: jotavare/latex:latest
    container_name: latex_container
    restart: unless-stopped